version: "3.3"
services:
  web:
    image: node:18
    user: ${RUNAS}
    ports:
      - "3000:3000"
    volumes:
      - ../:/tmp/src
      - ../.docker-volumes/home:/tmp/home
      - ../.docker-volumes/var:/var/lib/project
    environment:
      HOME: /tmp/home
    working_dir: /tmp/src
    command: sh -c 'sleep 5; npm run dev -- --port 3000 --host'
